package live.gavesh.pages;

import java.awt.Desktop;
import java.io.File;
import java.net.URI;
import live.gavesh.pages.view.*;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import live.gavesh.util.DatabaseHelper;
import javax.swing.*;
import live.gavesh.data.Student;
import live.gavesh.pages.view.ViewAllTeachersForm;
import live.gavesh.util.ReportHelper;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author gav
 */
public class DashboardForm extends JFrame {

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        this.openProfileButton.setVisible(false);
        this.deleteStudentButton.setVisible(false);
        this.searchList.setModel(jList1Model);
        this.propertyTotalStudents.setText("Total Students - " + DatabaseHelper.getAllStudents().size());
        this.propertyTotalSubjects.setText("Total Subjects - " + DatabaseHelper.getAllSubjects().size());
        this.propertyAverageAttendance.setText("Average Attendance - " + DatabaseHelper.getOverallAttendancePercentage() + "%");
        this.searchList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    Object selectedItem = searchList.getSelectedValue();

                    if (selectedItem != null && !selectedItem.toString().isEmpty()) {
                        openProfileButton.setVisible(true);
                        deleteStudentButton.setVisible(true);
                    } else {
                        openProfileButton.setVisible(false);
                        deleteStudentButton.setVisible(false);
                    }

                    repaint();
                }
            }
        });
        this.loadStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        propertyTotalStudents = new javax.swing.JLabel();
        propertyAverageAttendance = new javax.swing.JLabel();
        propertyTotalSubjects = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        openProfileButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        searchButton1 = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        deleteStudentButton = new javax.swing.JButton();
        addTeacherButton = new javax.swing.JButton();
        addSubjectButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        viewTeachersButton = new javax.swing.JButton();
        viewAllSubjectsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        generateStudentReport = new javax.swing.JButton();
        generateTeacherReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        propertyTotalStudents.setBackground(new java.awt.Color(153, 0, 51));
        propertyTotalStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        propertyTotalStudents.setForeground(new java.awt.Color(255, 255, 255));
        propertyTotalStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTotalStudents.setText("Total Students");
        propertyTotalStudents.setOpaque(true);

        propertyAverageAttendance.setBackground(new java.awt.Color(153, 0, 51));
        propertyAverageAttendance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        propertyAverageAttendance.setForeground(new java.awt.Color(255, 255, 255));
        propertyAverageAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyAverageAttendance.setText("Overall Values");
        propertyAverageAttendance.setOpaque(true);
        propertyAverageAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertyAverageAttendanceMouseClicked(evt);
            }
        });

        propertyTotalSubjects.setBackground(new java.awt.Color(153, 0, 51));
        propertyTotalSubjects.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        propertyTotalSubjects.setForeground(new java.awt.Color(255, 255, 255));
        propertyTotalSubjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertyTotalSubjects.setText("Total Subjects");
        propertyTotalSubjects.setOpaque(true);

        openProfileButton.setText("Open Profile");
        openProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProfileButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(searchList);

        jLabel2.setText("Search All Students");

        searchButton1.setText("Search");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        deleteStudentButton.setText("Remove");
        deleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButtonActionPerformed(evt);
            }
        });

        addTeacherButton.setText("Add Teacher");
        addTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherButtonActionPerformed(evt);
            }
        });

        addSubjectButton.setText("Add Subject");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Quick Actions");

        jLabel4.setText("View Actions");

        viewTeachersButton.setText("View All Teachers");
        viewTeachersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTeachersButtonActionPerformed(evt);
            }
        });

        viewAllSubjectsButton.setText("View All Subjects");
        viewAllSubjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllSubjectsButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Generate PDF Reports");

        generateStudentReport.setText("Generate Low Performance");
        generateStudentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateStudentReportActionPerformed(evt);
            }
        });

        generateTeacherReport.setText("Generate Student Attendance");
        generateTeacherReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateTeacherReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(propertyTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertyTotalSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertyAverageAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewTeachersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAllSubjectsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateStudentReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateTeacherReport, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertyTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertyAverageAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertyTotalSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewTeachersButton)
                        .addComponent(generateStudentReport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTeacherButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewAllSubjectsButton)
                        .addComponent(generateTeacherReport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSubjectButton)
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProfileButtonActionPerformed
        Object selectedItem = searchList.getSelectedValue();
        if (selectedItem.toString().isEmpty()) {
            return;
        }
        new ViewStudentForm(DatabaseHelper.getStudentByName(selectedItem.toString()).getStudentId()).setVisible(true);
    }//GEN-LAST:event_openProfileButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        loadStudents();
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void loadStudents() {
        String searchString = this.searchField.getText();
        DefaultListModel defModel = (DefaultListModel) searchList.getModel();
        defModel.clear();
        DatabaseHelper.getAllStudents().forEach((t) -> {
            if (t.getFullName().startsWith(searchString) || searchString.isEmpty()) {
                defModel.addElement(t.getFullName());
            }
        });
    }

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        new AddStudentForm().setVisible(true);
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void deleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentButtonActionPerformed
        Object selectedItem = searchList.getSelectedValue();
        if (selectedItem.toString().isEmpty()) {
            return;
        }
        Student student = DatabaseHelper.getStudentByName(selectedItem.toString());
        DatabaseHelper.deleteStudent(Integer.parseInt(student.getStudentId()));
        int choice = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete the student: " + student.getFullName() + " (ID: " + student.getStudentId() + ")?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            try {
                DatabaseHelper.deleteStudent(Integer.parseInt(student.getStudentId()));
                JOptionPane.showMessageDialog(null, "Student '" + student.getFullName() + "' deleted successfully.", "Deletion Successful", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error: Invalid student ID format for deletion. " + e.getMessage(), "Deletion Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "An error occurred during student deletion: " + e.getMessage(), "Deletion Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                loadStudents();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Student deletion cancelled.", "Deletion Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_deleteStudentButtonActionPerformed

    private void addTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherButtonActionPerformed
        AddTeacherForm teacherForm = new AddTeacherForm();
        teacherForm.setVisible(true);
    }//GEN-LAST:event_addTeacherButtonActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        AddSubjectForm subjectForm = new AddSubjectForm();
        subjectForm.setVisible(true);
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void viewTeachersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTeachersButtonActionPerformed
        ViewAllTeachersForm teachersForm = new ViewAllTeachersForm();
        teachersForm.setVisible(true);
    }//GEN-LAST:event_viewTeachersButtonActionPerformed

    private void viewAllSubjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllSubjectsButtonActionPerformed
        ViewAllSubjectsForm subjectsForm = new ViewAllSubjectsForm();
        subjectsForm.setVisible(true);
    }//GEN-LAST:event_viewAllSubjectsButtonActionPerformed

    private void propertyAverageAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertyAverageAttendanceMouseClicked
        System.out.println("!");
    }//GEN-LAST:event_propertyAverageAttendanceMouseClicked

    private void generateStudentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateStudentReportActionPerformed
        try {
            String filePath = ReportHelper.getReportHandler().compileStudentLowPerformanceReport();
            if (filePath != null) {
                File pdfFile = new File(filePath);
                Desktop.getDesktop().browse(pdfFile.toURI());
            }
            JOptionPane.showMessageDialog(this, "Report Generated!");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Could not open PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_generateStudentReportActionPerformed

    private void generateTeacherReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateTeacherReportActionPerformed
        try {
            String filePath = ReportHelper.getReportHandler().compileStudentAttendanceReport();
            if (filePath != null) {
                File pdfFile = new File(filePath);
                Desktop.getDesktop().browse(pdfFile.toURI());
            }
            JOptionPane.showMessageDialog(this, "Report Generated!");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Could not open PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_generateTeacherReportActionPerformed

    private DefaultListModel jList1Model = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JButton deleteStudentButton;
    private javax.swing.JButton generateStudentReport;
    private javax.swing.JButton generateTeacherReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openProfileButton;
    private javax.swing.JLabel propertyAverageAttendance;
    private javax.swing.JLabel propertyTotalStudents;
    private javax.swing.JLabel propertyTotalSubjects;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField searchField;
    private javax.swing.JList<String> searchList;
    private javax.swing.JButton viewAllSubjectsButton;
    private javax.swing.JButton viewTeachersButton;
    // End of variables declaration//GEN-END:variables
}
